{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Query1\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.782.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "4bb74731-072b-4f5c-b7e7-36f77c6457ac",
        "fromColumn": "Self-Registered Date",
        "fromTable": "Query1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a39c5ff4-19bc-46e8-9215-04b513653d7e"
      }
    ],
    "sourceQueryCulture": "en-CA",
    "tables": [
      {
        "name": "Query1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Evacuees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7e464348-c330-45c4-a585-8880dabb6abf",
            "sourceColumn": "Evacuees",
            "summarizeBy": "sum"
          },
          {
            "name": "Households",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75d39433-af9b-4418-8bc0-9322a814047b",
            "sourceColumn": "Households",
            "summarizeBy": "sum"
          },
          {
            "name": "Task Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f43cd56a-b68d-494e-b68e-b7d1dd69f64c",
            "sourceColumn": "Task Number",
            "summarizeBy": "none"
          },
          {
            "name": "Self-Registered Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "adf67db1-7549-4b65-a8c4-7ef8bb847584",
            "sourceColumn": "Self-Registered Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a39c5ff4-19bc-46e8-9215-04b513653d7e"
                },
                "isDefault": true,
                "relationship": "4bb74731-072b-4f5c-b7e7-36f77c6457ac"
              }
            ]
          },
          {
            "name": "RegistrationCompletedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40947fa2-5e38-4b79-96bb-e9cb485f4cbd",
            "sourceColumn": "RegistrationCompletedDate",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b191e7fa-2012-4457-bc23-3402b52957d9",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Host Local Community",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd997d22-2298-49c5-b10a-7643242478ee",
            "sourceColumn": "Host Local Community",
            "summarizeBy": "none"
          },
          {
            "name": "EvacuatedFromLocation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9ecd303-aba9-4922-bd5f-77c258956d86",
            "sourceColumn": "EvacuatedFromLocation",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6ff2e764-2131-4a50-99cd-9cab279c526a",
        "partitions": [
          {
            "name": "Query1-7e9692ea-abf7-450d-b332-cd1ad0acf1f0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"alight.idir.bcgov\", \"embc\", [Query=\"select count(era_householdmemberid) as Evacuees, count(distinct ef.era_evacuationfileid) as Households, et.era_name as TaskName, ef.era_evacuationfiledate as EvacuationFileDate, ef.era_registrationcompleteddate as RegistrationCompletedDate, ef.era_essfilestatusname as Status, et.era_jurisdictionidname as TaskLocation, ef.era_evacuatedfromidname as EvacuatedFromLocation#(lf)from [era_stage].era_householdmember hhm#(lf)left JOIN [era_stage].era_evacuationfile ef#(lf)ON hhm.era_evacuationfileid = ef.era_evacuationfileid#(lf)left JOIN [era_stage].[era_task] et#(lf)  ON et.era_taskid  = ef.era_taskid#(lf)where era_evacuationfiledate >= '2023-01-01' or era_registrationcompleteddate >= '2023-01-01'#(lf)group by ef.era_evacuationfiledate , ef.era_registrationcompleteddate , ef.era_essfilestatusname , et.era_jurisdictionidname , ef.era_evacuatedfromidname , et.era_name\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"EvacuationFileDate\", type date}, {\"RegistrationCompletedDate\", type date}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"EvacuationFileDate\", type text}, {\"RegistrationCompletedDate\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"EvacuationFileDate\", \"Self-Registered Date\"}, {\"TaskLocation\", \"Host Local Community\"}, {\"TaskName\", \"Task Number\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Self-Registered Date\", type date}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_dfe5f77d-8e2f-4cbf-bd9c-e796da2e46e2",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "40cc94c2-9293-4d4a-b87e-1384f94886c4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8ad9c738-d79e-4561-91a1-24d370d27641",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7608d76a-8b9b-4263-aa26-13fd097b85de",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0bd60d9e-eab6-4c16-8123-bc6e51dbc5fd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3622bdb2-bb53-40ff-b02f-3ecaf75ee0fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6813dd5c-5964-4fb9-b00c-382b3e3fcfd4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4941362d-3a16-4000-b37d-dc167d4a0b73",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f98b62b3-ac89-4458-a29f-c9bc282832be",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3581bf5b-98bf-4c99-a833-5ec39af5d33e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ae646c47-ef89-4136-b8c6-c5e43d19bfc9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f961b0ed-3425-4c6c-b229-c834c674bc1f",
                "ordinal": 3
              }
            ],
            "lineageTag": "7f06fe7e-ddca-488a-8473-c8d31712ee07"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "8c293ac7-05b8-4a98-ba2b-a171896f545d",
        "partitions": [
          {
            "name": "DateTableTemplate_dfe5f77d-8e2f-4cbf-bd9c-e796da2e46e2-36285b57-2371-4589-899d-ff470d0dd348",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a39c5ff4-19bc-46e8-9215-04b513653d7e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f84e69bc-11ab-43a9-a8a2-d05a21c6d6d7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bf38ba47-bc0f-4a65-9c41-2f816dc91265",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "35678ea0-c165-4912-8b92-313b5ea28bb1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0749b8e0-ee28-4d90-b86a-1e75ed58d95c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "633ac0c8-a445-4a4a-b96f-56c2f362bdcc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "abaea0e8-5166-4d97-b116-5e8d6f327805",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "99f727c0-52d3-4d3a-843d-206280ec5b43",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c06acc1e-01e8-4adc-895e-a13830ca60d5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9b9a2cca-a320-4ef1-9935-944e25c4ebbc",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3aaf4413-c427-4cbf-a029-69001571e5c0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ca5567b0-9c28-41ff-aea9-1cb685399059",
                "ordinal": 3
              }
            ],
            "lineageTag": "dcd64cf9-367c-4d1a-bf54-396c1ef17d35"
          }
        ],
        "isHidden": true,
        "lineageTag": "cd0e765b-bd95-40b2-8524-13a119fe2a1f",
        "partitions": [
          {
            "name": "LocalDateTable_a39c5ff4-19bc-46e8-9215-04b513653d7e-f870aabd-91bc-4ac4-b801-b69f58f984fc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Query1'[Self-Registered Date])), 1, 1), Date(Year(MAX('Query1'[Self-Registered Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}