// Learn more about DAX queries at https://aka.ms/dax-queries

// Here is a sample DAX query from your model, click 'Run'
// Try other DAX queries by right clicking a table, column, or measure in the data pane and choosing one from 'Quick queries'
EVALUATE
   VAR fact =  CALCULATETABLE(FactProject, FILTER(DimEventDetail, [EventID] = "2023 Freshet"), NOT(ISBLANK(FactProject[ProjectApprovedDate])))
    VAR both = NATURALINNERJOIN(fact, DimProjectDetail)
   
   RETURN SELECTCOLUMNS(both, [ProjectApprovedDate], [ProjectState])
	
	evaluate
	var Category = if( "Eligible" &&
	
	Applications Closed Eligible = calculate(countrows('FactCase'), FILTER('AllDates FactCase Bridge', 'AllDates FactCase Bridge'[DateKey] = "ClosePayStartedDate"), FILTER('DimCaseDetail', [EligibilityStatus] = "Eligible"), FILTER('DimCaseDetail', [CaseStatus] = "Closed"))
	
	Applications Closed Eligible = calculate(countrows('FactCase'), FILTER('AllDates FactCase Bridge', 'AllDates FactCase Bridge'[DateKey] = "ClosePayStartedDate"), FILTER('DimCaseDetail', [EligibilityStatus] = "Eligible", Withdrawn), FILTER('DimCaseDetail', [CaseStatus] = "Closed"))
	
	Applications Under Review = calculate(countrows('FactCase'), FILTER('AllDates FactCase Bridge', 'AllDates FactCase Bridge'[DateKey] = "CreatedDate"), FILTER('DimCaseDetail', [BPFStage] = "Checking Criteria"))
	
	Applications Assigned to Evaluator = calculate(countrows('FactCase'), FILTER('AllDates FactCase Bridge', 'AllDates FactCase Bridge'[DateKey] = "CreatedDate"), FILTER('DimCaseDetail', [BPFStage] = "Assess Damage"))
	
	Applications Waiting on Payment = calculate(countrows('FactCase'), FILTER('AllDates FactCase Bridge', 'AllDates FactCase Bridge'[DateKey] = "CreatedDate"), FILTER('DimCaseDetail', [BPFStage] = "Review Report"))