{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.140.1577.0 (25.02)+00af0910c5ca19a229c472b0dfc17a2c488f6b0a"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"src_emcr_readinessindexsurvey\",\"trans_Year\",\"trans_Scores\",\"trans_Answers\",\"trans_FieldsQuestions\",\"trans_Ministry\",\"trans_MaturityLevel\",\"Ministry\",\"Year\",\"Answers\",\"Score\",\"MaturityLevel\",\"Facts\",\"src_FieldsQuestions\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "answers.emcr_areteammembersawarename": {
                "Binding": {
                  "ConceptualEntity": "Answers",
                  "ConceptualProperty": "emcr_areteammembersawarename"
                },
                "State": "Generated"
              },
              "answers.emcr_awarenesscomments": {
                "Binding": {
                  "ConceptualEntity": "Answers",
                  "ConceptualProperty": "emcr_awarenesscomments"
                },
                "State": "Generated"
              },
              "answers.emcr_isministryexecutiveawarename": {
                "Binding": {
                  "ConceptualEntity": "Answers",
                  "ConceptualProperty": "emcr_isministryexecutiveawarename"
                },
                "State": "Generated"
              },
              "answers.has_the_ministry_business_continuity_advisor_received_training_from_a_business_continuity_management_program_certification_body": {
                "Binding": {
                  "ConceptualEntity": "Answers",
                  "ConceptualProperty": "Has the Ministry Business Continuity Advisor received training from a Business Continuity Management Program certification body?"
                },
                "State": "Generated"
              }
            },
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "trans_Answers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = src_emcr_readinessindexsurvey,",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"emcr_name\", \"emcr_ministry\", \"emcr_ministryname\", \"emcr_ministrybusinesscontinuityadvisorname\", \"emcr_isbusinesscontinuitydiscussedname\", \"emcr_hasexecutivesponsorname\", \"emcr_isplanimplementedname\", \"emcr_hassteeringcommitteename\", \"emcr_trainingreceivedname\", \"emcr_establishedprogramstructurename\", \"emcr_isministryexecutiveawarename\", \"emcr_areteammembersawarename\", \"emcr_annualawarenesscampaignname\", \"emcr_biaquantity\", \"emcr_biasreviewed\", \"emcr_biasapproved\", \"emcr_ministrylistuptodate\", \"emcr_ministrylistuptodatename\", \"emcr_criticalservicesannuallyreviewedname\", \"emcr_recoveryservicesannuallyreviewedname\", \"emcr_hasnotificationandactivationproceduresname\", \"emcr_hassitetempproceduresname\", \"emcr_containsmanualproceduresname\", \"emcr_lostdatainstructionsname\", \"emcr_communicationmethods\", \"emcr_altsitesindependentconnectivityname\", \"emcr_altsiteshavegeneratorname\", \"emcr_arerecordsbackedupname\", \"emcr_isrecoveryalternateidentifiedname\", \"emcr_itdrplansforcriticalsystemsname\", \"emcr_dortosmatchname\", \"emcr_ownersbiatrainingname\", \"emcr_strategyselectiontrainingname\", \"emcr_recoveryproceduretrainingname\", \"emcr_exercisetrainingname\", \"emcr_numberofbcps\", \"emcr_numberoforientations\", \"emcr_numberofdrills\", \"emcr_numberoftabletopexercises\", \"emcr_numberoffullscaleexercises\", \"emcr_numberoffunctionalexercises\", \"emcr_ismocannuallyreviewedname\", \"emcr_ismocalternateidentifiedname\", \"emcr_mocaltsiteprocedurename\", \"emcr_mocaltsitegeneratorname\", \"emcr_moccrisiscommunicationplanname\", \"emcr_mocstaffingplanname\", \"emcr_mocoverviewavailablename\", \"emcr_isics100offeredname\", \"emcr_mocactivationtrainingname\", \"emcr_ismocstafftrainedname\", \"emcr_ismocleadershiptrainedname\", \"emcr_mocstafforientationname\", \"emcr_moccommunicationsdrillname\", \"emcr_moctabletopconductedname\", \"emcr_havemocexercisesoccurredname\", \"emcr_mocfullscaleparticipationname\", \"emcr_criticaldependenciesidentifiedname\", \"emcr_criticaldependenciesprioritizedname\", \"emcr_haslossstrategyname\", \"emcr_criticalvendorannualplanparticipationname\", \"emcr_ministryexecapprovalname\", \"emcr_mocaltsiteconnectivityname\", \"emcr_isescalatedname\", \"emcr_leadershipcomments\", \"emcr_awarenesscomments\", \"emcr_criticalservicescomments\", \"emcr_bcpcomments\", \"emcr_recoverystrategiescomments\", \"emcr_crisismanagementcomments\", \"emcr_businesscontinuityexercisescomments\", \"emcr_mocexercisescomments\", \"emcr_supplychainmanagementcomments\", \"emcr_moctrainingcomments\", \"emcr_yearname\", \"emcr_businesscontinuityexercisesname\", \"emcr_altsiteshavegeneratordescription\", \"emcr_altsitesindependentconnectivitydescription\", \"emcr_itdrplansforcriticalsystemsdescription\", \"emcr_dortosmatchdescription\", \"emcr_hassitetempproceduresdescription\", \"emcr_businesscontinuitytrainingcomments\", \"emcr_altsitereadiness1\", \"emcr_mocaltsiteinfrastructure\", \"emcr_bcpfullscalerecoveryname\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"emcr_yearname\", \"Year\"}, {\"emcr_name\", \"EMCRName\"}, {\"emcr_ministry\", \"MinistryID\"}, {\"emcr_ministryname\", \"MinistryName\"}}),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Renamed Columns\",#\"trans_FieldsQuestions\", MissingField.Ignore),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"26. Has the ministry conducted a full-scale Business Continuity Plan (BCP) recovery exercise, integrating notification, activation, manual processes, and IT recovery, with documented lessons learned and improvements made?\", type text}}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"26. Has the ministry conducted a full-scale Business Continuity Plan (BCP) recovery exercise, integrating notification, activation, manual processes, and IT recovery, with documented lessons learned and improvements made?\", \"26. Has the ministry conducted...\"}, {\"32. Are IT Disaster Recovery (ITDR) plans in place for the ministry systems identified as critical, and do the Recovery Time Objectives (RTOs) of ministry critical systems align with the RTOs of the critical services dependent on them?\", \"32. Are IT Disaster Recovery (ITDR)\"}, {\"30. Have the records and data required to support recovery been backed up to a source that is accessible if the network is unavailable?\", \"30. Have the records and data\"}, {\"49. Does the MOC alternate site have essential infrastructure, including setup procedures, power, water, internet, and connectivity solutions, to support operations?\", \"49. Does the MOC alternate site\"}})",
          "in",
          "    #\"Renamed Columns1\""
        ],
        "kind": "m",
        "lineageTag": "a3c10fc1-476e-4628-86dc-09a0ad516171",
        "queryGroup": "Transform"
      },
      {
        "name": "src_emcr_readinessindexsurvey",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = CommonDataService.Database(\"emcrdev.crm3.dynamics.com\"),",
          "    dbo_emcr_readinessindexsurvey = Source{[Schema=\"dbo\",Item=\"emcr_readinessindexsurvey\"]}[Data],",
          "     #\"Removed Other Columns\" = Table.SelectColumns(dbo_emcr_readinessindexsurvey,{\"emcr_name\", \"emcr_ministry\", \"emcr_ministryname\", \"emcr_ministrybusinesscontinuityadvisorname\", \"emcr_isbusinesscontinuitydiscussedname\", \"emcr_hasexecutivesponsorname\", \"emcr_isplanimplementedname\", \"emcr_hassteeringcommitteename\", \"emcr_trainingreceivedname\", \"emcr_establishedprogramstructurename\", \"emcr_isministryexecutiveawarename\", \"emcr_areteammembersawarename\", \"emcr_annualawarenesscampaignname\", \"emcr_biaquantity\", \"emcr_biasreviewed\", \"emcr_biasapproved\", \"emcr_ministrylistuptodate\", \"emcr_ministrylistuptodatename\", \"emcr_criticalservicesannuallyreviewedname\", \"emcr_recoveryservicesannuallyreviewedname\", \"emcr_hasnotificationandactivationproceduresname\", \"emcr_hassitetempproceduresname\", \"emcr_containsmanualproceduresname\", \"emcr_lostdatainstructionsname\", \"emcr_communicationmethods\", \"emcr_altsitesindependentconnectivityname\", \"emcr_altsiteshavegeneratorname\", \"emcr_arerecordsbackedupname\", \"emcr_isrecoveryalternateidentifiedname\", \"emcr_itdrplansforcriticalsystemsname\", \"emcr_dortosmatchname\", \"emcr_ownersbiatrainingname\", \"emcr_strategyselectiontrainingname\", \"emcr_recoveryproceduretrainingname\", \"emcr_exercisetrainingname\", \"emcr_numberofbcps\", \"emcr_numberoforientations\", \"emcr_numberofdrills\", \"emcr_numberoftabletopexercises\", \"emcr_numberoffullscaleexercises\", \"emcr_numberoffunctionalexercises\", \"emcr_ismocannuallyreviewedname\", \"emcr_ismocalternateidentifiedname\", \"emcr_mocaltsiteprocedurename\", \"emcr_mocaltsitegeneratorname\", \"emcr_moccrisiscommunicationplanname\", \"emcr_mocstaffingplanname\", \"emcr_mocoverviewavailablename\", \"emcr_isics100offeredname\", \"emcr_mocactivationtrainingname\", \"emcr_ismocstafftrainedname\", \"emcr_ismocleadershiptrainedname\", \"emcr_mocstafforientationname\", \"emcr_moccommunicationsdrillname\", \"emcr_moctabletopconductedname\", \"emcr_havemocexercisesoccurredname\", \"emcr_mocfullscaleparticipationname\", \"emcr_criticaldependenciesidentifiedname\", \"emcr_criticaldependenciesprioritizedname\", \"emcr_haslossstrategyname\", \"emcr_criticalvendorannualplanparticipationname\", \"emcr_ministryexecapprovalname\", \"emcr_mocaltsiteconnectivityname\", \"emcr_isescalatedname\", \"emcr_leadershipcomments\", \"emcr_awarenesscomments\", \"emcr_criticalservicescomments\", \"emcr_bcpcomments\", \"emcr_recoverystrategiescomments\", \"emcr_crisismanagementcomments\", \"emcr_businesscontinuityexercisescomments\", \"emcr_mocexercisescomments\", \"emcr_supplychainmanagementcomments\", \"emcr_moctrainingcomments\", \"emcr_yearname\", \"emcr_businesscontinuityexercisesname\", \"emcr_altsiteshavegeneratordescription\", \"emcr_altsitesindependentconnectivitydescription\", \"emcr_itdrplansforcriticalsystemsdescription\", \"emcr_dortosmatchdescription\", \"emcr_hassitetempproceduresdescription\", \"emcr_businesscontinuitytrainingcomments\", \"emcr_level1foundational\", \"emcr_level2initialprogress\", \"emcr_level3moderateprogress\", \"emcr_level4substantialprogress\", \"emcr_level5objectiveachieved\", \"emcr_altsitereadiness1\", \"emcr_mocaltsiteinfrastructure\", \"emcr_totalscoreleadershippercentage\", \"emcr_totalscorebcmpawarenesspercentage\", \"emcr_totalscorebcppercentage\", \"emcr_totalscorerecoverystrategiespercentage\", \"emcr_totalscorecriticalservicespercentage\", \"emcr_totalscorebctpercentage\", \"emcr_totalscorebcepercentage\", \"emcr_totalscorecrisismgmtpercentage\", \"emcr_totalscoremocexercisespercentage\", \"emcr_totalscoremoctrainingpercentage\", \"emcr_totalscorepercentage\", \"emcr_totalscoreapprovalpercentage\", \"emcr_totalscorescmpercentage\", \"emcr_bcpfullscalerecoveryname\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each ([emcr_ministry] <> null))",
          "in",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "93f80065-f362-47cd-9a6e-128706d5ef19",
        "queryGroup": "Source"
      },
      {
        "name": "trans_Year",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = src_emcr_readinessindexsurvey,",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"emcr_yearname\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"emcr_yearname\", \"Year\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each ([Year] <> null))",
          "in",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "0bc5bd7d-0f8f-4c9f-abd6-6703230b8945",
        "queryGroup": "Transform"
      },
      {
        "name": "trans_Scores",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = src_emcr_readinessindexsurvey,",
          "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"emcr_name\", \"EMCRName\"}, {\"emcr_ministry\", \"MinistryID\"}, {\"emcr_ministryname\", \"MinistryName\"}, {\"emcr_yearname\", \"Year\"}, {\"emcr_level1foundational\", \"Level 1 Foundational\"}, {\"emcr_level2initialprogress\", \"Level 2 Initial Progress\"}, {\"emcr_level3moderateprogress\", \"Level 3 Moderate Progress\"}, {\"emcr_level4substantialprogress\", \"Level 4 Substantial Progress\"}, {\"emcr_level5objectiveachieved\", \"Level 5 Objective Achieved\"}, {\"emcr_totalscoreleadershippercentage\", \"Total Score Leadership\"}, {\"emcr_totalscorebcmpawarenesspercentage\", \"Total Score BCMP Awareness\"}, {\"emcr_totalscorebcppercentage\", \"Total Score BCP\"}, {\"emcr_totalscorerecoverystrategiespercentage\", \"Total Score Recovery Strategies\"}, {\"emcr_totalscorecriticalservicespercentage\", \"Total Score Critical Services\"}, {\"emcr_totalscorebctpercentage\", \"Total Score BCT\"}, {\"emcr_totalscorebcepercentage\", \"Total Score BCE\"}, {\"emcr_totalscorecrisismgmtpercentage\", \"Total Score Crisis Management\"}, {\"emcr_totalscoremocexercisespercentage\", \"Total Score MOS Exercises\"}, {\"emcr_totalscoremoctrainingpercentage\", \"Total Score MOC Training\"}, {\"emcr_totalscorepercentage\", \"Total Score\"}, {\"emcr_totalscoreapprovalpercentage\", \"Total Score Approval\"}, {\"emcr_totalscorescmpercentage\", \"Total Score CM\"}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Level 1 Foundational\", \"Level 2 Initial Progress\", \"Level 3 Moderate Progress\", \"Level 4 Substantial Progress\", \"Level 5 Objective Achieved\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "c80c9cf6-2dc5-40d0-b4b1-6c2b9197965d",
        "queryGroup": "Transform"
      },
      {
        "name": "trans_Ministry",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = src_emcr_readinessindexsurvey,",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"emcr_ministryname\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"emcr_ministryname\", \"MinistryName\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "faf5ca3b-6df0-4084-b697-d3430a5d02fd",
        "queryGroup": "Transform"
      },
      {
        "name": "trans_MaturityLevel",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = src_emcr_readinessindexsurvey,",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"emcr_name\", \"emcr_ministryname\", \"emcr_yearname\", \"emcr_level1foundational\", \"emcr_level2initialprogress\", \"emcr_level3moderateprogress\", \"emcr_level4substantialprogress\", \"emcr_level5objectiveachieved\"}),",
          "    #\"Unpivoted Columns\" = Table.UnpivotOtherColumns(#\"Removed Other Columns\", {\"emcr_name\", \"emcr_ministryname\", \"emcr_yearname\"}, \"Attribute\", \"Value\"),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Unpivoted Columns\",\"emcr_level\",\"Level \",Replacer.ReplaceText,{\"Attribute\"}),",
          "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"foundational\",\" Foundational\",Replacer.ReplaceText,{\"Attribute\"}),",
          "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"initialprogress\",\" Initial Progress\",Replacer.ReplaceText,{\"Attribute\"}),",
          "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"moderateprogress\",\" Moderate Progress\",Replacer.ReplaceText,{\"Attribute\"}),",
          "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"substantialprogress\",\" Substantial Progress\",Replacer.ReplaceText,{\"Attribute\"}),",
          "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"objectiveachieved\",\" Objective Achieved\",Replacer.ReplaceText,{\"Attribute\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Replaced Value5\",{{\"emcr_name\", \"EMCRName\"}, {\"emcr_ministryname\", \"Ministry\"}, {\"emcr_yearname\", \"Year\"}, {\"Attribute\", \"Maturity Level\"}, {\"Value\", \"Percent Score\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "62567fe5-299d-45ed-abd0-142e49b83c5e",
        "queryGroup": "Transform"
      },
      {
        "name": "trans_FieldsQuestions",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "List"
          }
        ],
        "expression": [
          "let",
          "    Source = src_FieldsQuestions,",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Field] <> \"\" and [Field] <> \"emcr_ministry\")),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",\" \",\"\",Replacer.ReplaceText,{\"Field\"}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Replaced Value\", \"ChangeList\", each {[Field],[Question]}),",
          "    ChangeList = #\"Added Custom\"[ChangeList]",
          "in",
          "    ChangeList"
        ],
        "kind": "m",
        "lineageTag": "4734644a-8b13-4743-9a5f-5bcd4065da99",
        "queryGroup": "Transform"
      },
      {
        "name": "src_FieldsQuestions",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"tVnrTiS7EX4Vi1+sNOFwZ/mFYGAVpKBFC1EUrY4iT7cHnO1u97G7IZOnOc9ynixf+dbuGzObKNL+2BnK9VWV6/KV5/v3vQdZSdPozd5iT5SZ/kfZfT46YH975Q0LIuxaC/Z31bJvola6kdUL+6L01d6vi+97fxE8F9q8ynqoaNUaWQljMlXhSCubDc/fpFG64qWA8PEBu1XCsOZVsHCGvfI3wXiHfLN8YNfu2ByeNGOkXJqsNUbkHuvkgN0bduPl2DIKsgde8RdRiqphj1q9aF6yfYA+fmJRB0MoyEjxL5G1jYSBhXgTxZw9r9xESVOrqvP4NPGYHKs9oHO6SgD8uSs263Nd8EqWdWFNj36eHbA/80FIEylEdscY1KqQ2YYpzaCDN+JFZowgJ5zGv/MD9kUWgv21LhTP5+NiGiE00idTZSkbfPBmX0ylwjhCLJxnUcFshIr4DcnCNYO/fD5gnSQi4P9AGq7fuRYUmKAAbsOS6kWLTOBKQoQvuwh3SToRU5+0LBxnQR9ba1VuvYg/fg83kQlU3FpmvJGqYiuVb66mDRam4atCmleR+7DBuDZrWh3CfHRoywC2a5dv3QlWieZd6R9Mre09M/VeIUyQyn+BF5lSOpcVb5Q2M/DShJuLacytjMdGU6E2Eq+3S3YrRsChLrzrM0D42AiOqytXsLCHcewwpkJLR5g/00OUuCNViDm3eFW1vODh64yXNZcvVUA86UfUSf/x+86X69WxRlGul6qBmqJAovP1mkXUOduiVV2KH6HJRMF+ii+1bJBHBXsS+k1mIupZSf5by2FoY7s/NRH1zkpeJal9D0Ozhl1XvNgYlOr+zf21QZOkst2oVncXq8VvrdTiaium0eJNineRE+j5LqDvFOZwinKTtXXOqbHJih0fHp/tAMprBPrNgV7Mg5qRqxY8nLadEReH/62iyznrus4WS0K0UH1NWzeKvAg59Xl+MFZwmHKFxBmd7ZI4C1DGQ22xIMgHcZe6xSaEN1hz6WpqpJ6FA/0L8UFRSF8EJrbIu1DtW6xCu0R49WaLVceH01axcD6Orf+XocPwJSV4jFY3OtcvxZvlYzIWK9V1eJiG7JNv9gNyLRM5GrgJfh/3KMQj8j4r2lywVIV1r1PCOi1XE+BGNuinZT3GOpnBylRh8x9dpmR0HNFvKDGngejfAJaIGqahQeHhZsbIpwNkL8+c/EcOFco0KA5Sbocf/I9az2a0prJs7Wa2FtzyXNJH1cZHSKusXrdFgYlQiJB1Ael8goYBLQeIJWF08E/25OSseqQBDBYKEhrzGeNSZ9KIBcxFXmtnXnrti+TOF71QgcSahc2K++eoccHeZfOKBp61nhxiCBoKAZqYrnyVgDxSv7OZC525mIpDmvtoqRTbXrZ/85Dd9ZdlW3mzS9G8qtye/ez3Dv8V9baeKCzGbFwJ1lpWvm6ERjDB0zmIod8Phli8aChFcZ+5jfMRAV0mmQABAYJOWUypbPssRQy3gfjJaq155FHUekukjE0bVQttzTIj5JDyI2O0TRWdmxXPfiCF67CfHFLGAJks8iI2/pR63XgBvGlr2sG6xFiBRTOnzg8H8GQM5IyUIZgSijLKAblCuknHsgLbwx/bir9xWYAIiukIShOwYqhkTuFZy26/OqKI2psPx9lzyrjC+IoqZrCaXBP9NCjD2GE3uN0yVPGJ53jI5Ft/8R3k/v3z7bdPlsAaogT4D8JAJd0rRa+RdW4wVGvAc5WSK3um80aWgn1d/VNkdq9j+9+ev4IUIEW7Co/DyOvnBVE7W2ZWF04Emjsep7moRUUGMSQ6RMqdsyrOzDjykoI8QRePTjx1Q3Ewjp6DMsf7QZTCvhLifuozNF0FbKTSdSFuO9MUTjoy9SkuQ1dDeO8D5n8hbEcemnHmzRgsKX2zxksXYupve0MfLQFwEPg0QRpGhgWZOHuGhp3/14a9Uy6kZoznWzQjjIEh+oVHX25FCxqQcESBXLKLQhLyCG6FAKEkA8pnjzI1tJbDvLBT7OsgL1zzoXbE4Wi0C7X6ccYsppI4+fIxhsyV713w8tZ6OXZs9GQUbElrB3NiytXnYPagiO6C9qqlrqfWmI2k5/Rwas8YDHxjJ/70SkXd82oORGkJG9wkIrCjHcBYeoipLGu1Hm5R0/7kGjPY4hzvguPE3e7UMaBtOPQsIRoMWH+LFu9kF7xwMqb5T2Ov28o2HpCzFP10F/Tu7P+C70llD35yJx/D09OBpZU/DT8uiKgiqYjT8+mKuItwwxcHquDu5SN5LFLZzG53epE8sX1dOtcsy5lc5Oh5yr8CXO0COsthTtO9m4BvwbkytLM58jIL5GCITvbpI4FcDkB+hn4u/ApGrQcjoLdxLVitcNVg9dCl3ZYAFt8s/BCqKstc6LKMKlpb+IuUUA7p7EfeZfZvPW5OYy88Qh8OfPSvt17jskfpH+Oj8keA9j0MbqcoR9Modv4S5eN5ron2UrD8cfBd04ptDjrvyvh9kv9nxwdsdK6f82RKGBCJBzSmKGkj2Q5uuBdE2EwHgxSLYvaKyPyrWe0wJzNHh4foHaj1+FPAqSuj++UTwx9dBXkRUnqzfPiFtG1RTrkc18oB6zg7c6+fCbuYSeufcydcuFXcORQYVrTa+eSlPLrUKARg2sFm6WnYgLcgdk93A9iLBDb59WC/1yII6Tr4jCGeWvZhcCdoxxkaUSo9zq+7ZDT0SiQZ68F8/4NFSLBOwNlI6z1aoU2JiXSYQurVvbET3oOdH/bAepVu2K126ztQ4zz6GClM8ygecI56OM9h6EfWtzMINQ0AxVkXqFAAOvZA7Es32lNFkTt97Egc6jXX2PtknV7R+Ul/4HUybl733ovoxxitMH1fqFdUtv8E6z+2YWqen58e9NwZzO+n5cPwvTOsqRn492iEnoftLK63qbi7le7Q1S4YtZaKvv53B3K+HSQ5xVbcuO6Avv1jhPnKTYFwhr0zYFy4V4bkFXn0nEDH7BNVMOMNRsSlGHdIm8+sj07YMRoaWZOJYRnJGCBJEJsfgRm52efIESUKp7Zn6DpHZpisDO+IXWAvd3+2xGSVBVoJvTIJ9zPE5HWklMWbv4jBcdyECAg4XfZKj7bjV8n0BXLshj1rj07O6ws0pCenf0lC01P71/8A\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, Field = _t, Question = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Category\", type text}, {\"Field\", type text}, {\"Question\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "d1074651-2660-40a3-84c2-824286bed458",
        "queryGroup": "Source"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Source"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Transform"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Presentation"
      }
    ],
    "relationships": [
      {
        "name": "ea3b43f7-fd72-1ff0-d5c7-b9d92908a1e9",
        "fromColumn": "Year",
        "fromTable": "Score",
        "toColumn": "Year",
        "toTable": "Year"
      },
      {
        "name": "6b9b7d6c-3686-f52d-19b4-dbe73f0291c2",
        "fromColumn": "Year",
        "fromTable": "MaturityLevel",
        "toColumn": "Year",
        "toTable": "Year"
      },
      {
        "name": "f83ff86d-7d9f-cd87-1b2d-f9c56dac2180",
        "fromColumn": "MinistryName",
        "fromTable": "Score",
        "toColumn": "MinistryName",
        "toTable": "Ministry"
      },
      {
        "name": "3badf463-415f-053f-d62b-b602af8ef629",
        "fromColumn": "Ministry",
        "fromTable": "MaturityLevel",
        "toColumn": "MinistryName",
        "toTable": "Ministry"
      },
      {
        "name": "06102200-0c14-aa06-7132-3e7e3d07eb69",
        "fromColumn": "MinistryName",
        "fromTable": "Answers",
        "toColumn": "MinistryName",
        "toTable": "Ministry"
      },
      {
        "name": "73da6d9f-1fd3-6b09-be95-e5eceb127ee3",
        "fromColumn": "Year",
        "fromTable": "Answers",
        "toColumn": "Year",
        "toTable": "Year"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Ministry",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "MinistryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a67737a-e3c9-4d9d-8e99-3b771aed244e",
            "sourceColumn": "MinistryName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "70907f1a-15fd-4c48-b8fe-43c59f9a794a",
        "partitions": [
          {
            "name": "Ministry",
            "mode": "import",
            "queryGroup": "Presentation",
            "source": {
              "expression": [
                "let",
                "    Source = trans_Ministry",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Year",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea691150-ba41-4384-a8e2-66d2b7f6de33",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bd3f5918-c2fc-4178-9c06-e33ed4ea78ba",
        "partitions": [
          {
            "name": "Year",
            "mode": "import",
            "queryGroup": "Presentation",
            "source": {
              "expression": [
                "let",
                "    Source = trans_Year",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Score",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EMCRName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "364f0d86-76c9-464a-99f2-9bbcf7045103",
            "sourceColumn": "EMCRName",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          },
          {
            "name": "MinistryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95d7d5ce-f3dd-4766-994d-8c9e87e9c472",
            "sourceColumn": "MinistryID",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          },
          {
            "name": "MinistryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62aa23e1-76dc-4b23-b9d8-3b4f87e3f310",
            "sourceColumn": "MinistryName",
            "sourceProviderType": "nvarchar(160)",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "741710f4-ca5a-4831-9f3d-9c0cd473133e",
            "sourceColumn": "Year",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          },
          {
            "name": "Total Score Leadership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e56cd3d9-666c-4dc9-bb17-dd130e86adf1",
            "sourceColumn": "Total Score Leadership",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score BCMP Awareness",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b5faabcb-e548-4c42-b23f-8d4f495f2581",
            "sourceColumn": "Total Score BCMP Awareness",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score BCP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fbbeb3d4-20d9-42a4-9200-bb66c92b81fe",
            "sourceColumn": "Total Score BCP",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score Recovery Strategies",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67aae0b4-9831-4650-85b7-c6c7b4032a27",
            "sourceColumn": "Total Score Recovery Strategies",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score Critical Services",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6e903705-f430-4672-9112-ad3254bb2e72",
            "sourceColumn": "Total Score Critical Services",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score BCT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb4ee751-302e-40be-8094-71282bf19c1c",
            "sourceColumn": "Total Score BCT",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score BCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8ad98a9e-6b1f-4483-88a8-13d2e8af08ea",
            "sourceColumn": "Total Score BCE",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score Crisis Management",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5261e96b-c75f-44f6-b72a-d18ea54c06e2",
            "sourceColumn": "Total Score Crisis Management",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score MOS Exercises",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "78a29a07-43ac-4beb-a9d8-4ae2e45ec650",
            "sourceColumn": "Total Score MOS Exercises",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score MOC Training",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dab98e7e-905c-40bd-8559-3fcb0cf9f549",
            "sourceColumn": "Total Score MOC Training",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "176c9592-114b-4109-b127-476fb06bc982",
            "sourceColumn": "Total Score",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score Approval",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5947727-c6fc-4f8a-b1ab-5228c221150c",
            "sourceColumn": "Total Score Approval",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Score CM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cef8a230-79be-48e8-a0b9-3d29802f15e7",
            "sourceColumn": "Total Score CM",
            "sourceProviderType": "decimal(38, 0)",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_ministrybusinesscontinuityadvisorname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "455795d5-983f-4688-b336-15e71f0b9aff",
            "sourceColumn": "emcr_ministrybusinesscontinuityadvisorname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_isbusinesscontinuitydiscussedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6430f5e7-6b3b-4a4b-ae12-2f916dbac6e2",
            "sourceColumn": "emcr_isbusinesscontinuitydiscussedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_hasexecutivesponsorname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42b184d9-fcf4-4f1b-947c-99539bb4e824",
            "sourceColumn": "emcr_hasexecutivesponsorname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_isplanimplementedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74845338-15c7-4093-a2f0-88596688eb51",
            "sourceColumn": "emcr_isplanimplementedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_hassteeringcommitteename",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fb3e705-bbe4-4914-8144-25b41d69dfdc",
            "sourceColumn": "emcr_hassteeringcommitteename",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_trainingreceivedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4780ef5a-cf57-416c-b13e-d9100bcbb98f",
            "sourceColumn": "emcr_trainingreceivedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_establishedprogramstructurename",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1450fba-9bd7-417c-aeee-7105c950c915",
            "sourceColumn": "emcr_establishedprogramstructurename",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_isministryexecutiveawarename",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24613c3b-2236-415e-a36b-ca15476bd11e",
            "sourceColumn": "emcr_isministryexecutiveawarename",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_areteammembersawarename",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4db88b0e-2e1f-4568-a8b2-ebf866161420",
            "sourceColumn": "emcr_areteammembersawarename",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_annualawarenesscampaignname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5aa2efe9-3faf-4f60-b805-5911ff658b96",
            "sourceColumn": "emcr_annualawarenesscampaignname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_ministrylistuptodatename",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b65498da-c08c-45f7-9564-ff491da462a0",
            "sourceColumn": "emcr_ministrylistuptodatename",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_criticalservicesannuallyreviewedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea1a4535-a788-414e-ada0-b2cd42abadaf",
            "sourceColumn": "emcr_criticalservicesannuallyreviewedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_recoveryservicesannuallyreviewedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87083701-73f2-40ca-afe7-bbe2b0ae815b",
            "sourceColumn": "emcr_recoveryservicesannuallyreviewedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_hasnotificationandactivationproceduresname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "795857f1-a8c7-4ff4-8c8d-12fdc5d90413",
            "sourceColumn": "emcr_hasnotificationandactivationproceduresname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_hassitetempproceduresname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bf97379-8a2a-4c65-83a1-4f3e5277e09b",
            "sourceColumn": "emcr_hassitetempproceduresname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_containsmanualproceduresname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c8b1456-e4fd-4c8c-8ee3-08c522d0874d",
            "sourceColumn": "emcr_containsmanualproceduresname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_lostdatainstructionsname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bfdcfc6-3cd6-40bb-a676-546d8212e267",
            "sourceColumn": "emcr_lostdatainstructionsname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_communicationmethods",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "947c1c0b-8ced-4ca8-9972-5f8419c65f2c",
            "sourceColumn": "emcr_communicationmethods",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_altsitesindependentconnectivityname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "411b0d18-98b0-48d9-81ee-e793d66f1794",
            "sourceColumn": "emcr_altsitesindependentconnectivityname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_altsiteshavegeneratorname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f17f2e18-e305-420a-acfd-a3c8b6e42962",
            "sourceColumn": "emcr_altsiteshavegeneratorname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_arerecordsbackedupname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a14a3511-d135-40f5-96ae-da3613c63dd0",
            "sourceColumn": "emcr_arerecordsbackedupname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_isrecoveryalternateidentifiedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4f023c1-37f4-4cdb-a768-20d9eeb9640c",
            "sourceColumn": "emcr_isrecoveryalternateidentifiedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_itdrplansforcriticalsystemsname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4426ffee-cd64-4f79-9d92-6b632b1313a4",
            "sourceColumn": "emcr_itdrplansforcriticalsystemsname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_dortosmatchname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4231f6dd-1f60-42b0-98ea-7ee4acbd9201",
            "sourceColumn": "emcr_dortosmatchname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_ownersbiatrainingname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99a1cb8a-8d2d-4ec7-979c-417c139666cc",
            "sourceColumn": "emcr_ownersbiatrainingname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_strategyselectiontrainingname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12944c49-d57c-49c6-b0d2-60004fff9d23",
            "sourceColumn": "emcr_strategyselectiontrainingname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_recoveryproceduretrainingname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e6fe7a3-6936-4c59-8f9e-0990f3c6311b",
            "sourceColumn": "emcr_recoveryproceduretrainingname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_exercisetrainingname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1835d18c-f1f5-4dce-ad02-95892c456268",
            "sourceColumn": "emcr_exercisetrainingname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_numberofbcps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f2b14199-918b-409d-a9eb-a609d61c9ad2",
            "sourceColumn": "emcr_numberofbcps",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_numberoforientations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "55a5cd7c-b761-49cb-95d3-f5b7521457b7",
            "sourceColumn": "emcr_numberoforientations",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_numberofdrills",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "362e6c87-f028-4270-ae02-ca906871163f",
            "sourceColumn": "emcr_numberofdrills",
            "sourceProviderType": "nvarchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_numberoftabletopexercises",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "69263467-1fc4-46de-b100-56eb60392c5d",
            "sourceColumn": "emcr_numberoftabletopexercises",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_numberoffullscaleexercises",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ccf0058-641e-4e96-b89a-6e53fac1c05a",
            "sourceColumn": "emcr_numberoffullscaleexercises",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_numberoffunctionalexercises",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1585489b-22b7-45ce-97b6-c7463558c56b",
            "sourceColumn": "emcr_numberoffunctionalexercises",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_ismocannuallyreviewedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7dbe40dc-8e96-4076-bf04-059fa1f9e493",
            "sourceColumn": "emcr_ismocannuallyreviewedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_ismocalternateidentifiedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "468640a1-c18d-4eaa-ba8d-f60542646437",
            "sourceColumn": "emcr_ismocalternateidentifiedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocaltsiteprocedurename",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc9b3b36-7a1e-43f0-8272-9360ca38b612",
            "sourceColumn": "emcr_mocaltsiteprocedurename",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocaltsitegeneratorname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ea9c137-b07a-44bb-bdf7-81ecac32a7c8",
            "sourceColumn": "emcr_mocaltsitegeneratorname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_moccrisiscommunicationplanname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0a34c50-0764-4ec7-a598-8e2d4339a381",
            "sourceColumn": "emcr_moccrisiscommunicationplanname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocstaffingplanname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc650aa5-12d1-4546-b310-505c8aa7628d",
            "sourceColumn": "emcr_mocstaffingplanname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocoverviewavailablename",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b50c603c-5051-4907-9df9-2c43400c9702",
            "sourceColumn": "emcr_mocoverviewavailablename",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_isics100offeredname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcbf8d99-a803-4b13-9164-f146b985cabe",
            "sourceColumn": "emcr_isics100offeredname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocactivationtrainingname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8090ff49-3e21-40fe-8f9a-136fbafd0b6a",
            "sourceColumn": "emcr_mocactivationtrainingname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_ismocstafftrainedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7154a2f5-750e-4cba-8c01-2f947682eaed",
            "sourceColumn": "emcr_ismocstafftrainedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_ismocleadershiptrainedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa5d6ec6-be92-4afc-85a8-7734344c8d2a",
            "sourceColumn": "emcr_ismocleadershiptrainedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocstafforientationname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dd29be9-c678-4339-9ef6-2ca1d46bbf50",
            "sourceColumn": "emcr_mocstafforientationname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_moccommunicationsdrillname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06151355-35d4-48ad-85a9-fa5ca4c4435d",
            "sourceColumn": "emcr_moccommunicationsdrillname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_moctabletopconductedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c384e27-a35e-4c0d-9b8f-14ae1ab7ae7b",
            "sourceColumn": "emcr_moctabletopconductedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_havemocexercisesoccurredname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abe21daf-e75e-493c-ba15-d494edf2556d",
            "sourceColumn": "emcr_havemocexercisesoccurredname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocfullscaleparticipationname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e55a87ad-53db-4f61-9f57-229cc6bdd841",
            "sourceColumn": "emcr_mocfullscaleparticipationname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_criticaldependenciesidentifiedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "957c17d8-1d69-47c8-8b45-5ceb724b1ad5",
            "sourceColumn": "emcr_criticaldependenciesidentifiedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_criticaldependenciesprioritizedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2af1e8b2-567c-401a-b1f7-a8e7540e1216",
            "sourceColumn": "emcr_criticaldependenciesprioritizedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_haslossstrategyname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8c2976c-8bb1-4798-9141-bb7d153a0068",
            "sourceColumn": "emcr_haslossstrategyname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_criticalvendorannualplanparticipationname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6008e8bb-d061-409b-a168-7832b53a64c6",
            "sourceColumn": "emcr_criticalvendorannualplanparticipationname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_ministryexecapprovalname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59c26fb2-930a-4b1a-a65f-9283165f5068",
            "sourceColumn": "emcr_ministryexecapprovalname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocaltsiteconnectivityname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8817025f-453f-41a8-afcc-3ab1ce60e310",
            "sourceColumn": "emcr_mocaltsiteconnectivityname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_isescalatedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a93ba914-ee05-4d74-b192-315b302a4246",
            "sourceColumn": "emcr_isescalatedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_leadershipcomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50c0ff11-b367-475a-979f-ec32c7c9e9df",
            "sourceColumn": "emcr_leadershipcomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_awarenesscomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8a18bda-5348-4bd2-837c-63c8257f423f",
            "sourceColumn": "emcr_awarenesscomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_criticalservicescomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0f8dfe8-e11f-4853-9ac3-1672dd2d75bf",
            "sourceColumn": "emcr_criticalservicescomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_bcpcomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "866f46f4-700e-478a-b519-ecf5f2af79a1",
            "sourceColumn": "emcr_bcpcomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_recoverystrategiescomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4d7720d-83a4-45d8-a208-58d95d8f7472",
            "sourceColumn": "emcr_recoverystrategiescomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_crisismanagementcomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b1b5df2-cb9a-4434-9f11-45051bc2321c",
            "sourceColumn": "emcr_crisismanagementcomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_businesscontinuityexercisescomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eaff0b04-296f-4f4b-ad33-9106284504af",
            "sourceColumn": "emcr_businesscontinuityexercisescomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocexercisescomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bcab5a1-0ea9-463f-9eb4-7523b92e4d33",
            "sourceColumn": "emcr_mocexercisescomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_supplychainmanagementcomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4788c56e-bd39-42fc-808b-cecff8dc9858",
            "sourceColumn": "emcr_supplychainmanagementcomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_moctrainingcomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7639d70f-a122-4b65-926b-74ff50bb6ac9",
            "sourceColumn": "emcr_moctrainingcomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_businesscontinuityexercisesname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01f89ffe-c7ba-4ac3-9cd2-33d3ece385e5",
            "sourceColumn": "emcr_businesscontinuityexercisesname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_altsiteshavegeneratordescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41ed9cd2-db00-408e-985c-180b0b4e753a",
            "sourceColumn": "emcr_altsiteshavegeneratordescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_altsitesindependentconnectivitydescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a28d6ea4-7c78-442e-8dae-538775f6e956",
            "sourceColumn": "emcr_altsitesindependentconnectivitydescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_itdrplansforcriticalsystemsdescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa801988-f322-402d-a3be-984ee73805af",
            "sourceColumn": "emcr_itdrplansforcriticalsystemsdescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_dortosmatchdescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5640c40c-2af7-4b09-bdee-7d5649850c88",
            "sourceColumn": "emcr_dortosmatchdescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_hassitetempproceduresdescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45f2b297-1632-4bd6-a883-504ce1f37b6b",
            "sourceColumn": "emcr_hassitetempproceduresdescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_businesscontinuitytrainingcomments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83545310-1f02-4e43-a2ef-433b8f2de699",
            "sourceColumn": "emcr_businesscontinuitytrainingcomments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_biaquantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d4df21b-2a0e-4ce0-bed7-639f08c9dd4a",
            "sourceColumn": "emcr_biaquantity",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_biasreviewed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3eddbf59-1051-4616-84a3-65d2067b7d84",
            "sourceColumn": "emcr_biasreviewed",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_biasapproved",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c93482f-45eb-4d6f-bc36-2fa5a3b5ddff",
            "sourceColumn": "emcr_biasapproved",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_ministrylistuptodate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "807036a0-d792-4d73-9710-8fd0b0033ed1",
            "sourceColumn": "emcr_ministrylistuptodate",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "emcr_bcpfullscalerecoveryname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70dd5422-6253-418f-a478-ef7b8a2ea466",
            "sourceColumn": "emcr_bcpfullscalerecoveryname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_altsitereadiness1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a7822b0-4005-4dbc-9021-a55efc905a35",
            "sourceColumn": "emcr_altsitereadiness1",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocaltsiteinfrastructure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcc26e49-7e10-4af6-ace3-3072f4e97f3b",
            "sourceColumn": "emcr_mocaltsiteinfrastructure",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0d3d831a-a19c-44e0-84c5-b4babe43e2e4",
        "partitions": [
          {
            "name": "Score",
            "mode": "directQuery",
            "queryGroup": "Presentation",
            "source": {
              "expression": [
                "let",
                "    Source = trans_Scores",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MaturityLevel",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EMCRName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "899622d6-7c7a-477d-a11b-20b84977e214",
            "sourceColumn": "EMCRName",
            "summarizeBy": "none"
          },
          {
            "name": "Ministry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad08f6d2-e23f-4b66-85eb-25eba7c49554",
            "sourceColumn": "Ministry",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "609c3111-1059-4c0f-b498-32f2ceb65c75",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Maturity Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f15ad4eb-d6c8-436d-84cc-b0180df1f0f2",
            "sourceColumn": "Maturity Level",
            "summarizeBy": "none"
          },
          {
            "name": "Percent Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0280a558-fb70-4009-8276-f06a41f9631b",
            "sourceColumn": "Percent Score",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0714bce1-a875-4bc6-a246-4fe6d5d8bd22",
        "partitions": [
          {
            "name": "MaturityLevel",
            "mode": "import",
            "queryGroup": "Presentation",
            "source": {
              "expression": [
                "let",
                "    Source = trans_MaturityLevel",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Facts",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Values",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b15a576d-7681-414e-8932-2123ff98ed98",
            "sourceColumn": "Values",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f73357af-ec52-48b1-9fa4-66ab805e67bd",
        "measures": [
          {
            "name": "Current",
            "expression": "\"Report Generated on \" & NOW()",
            "lineageTag": "6ea3b1ea-0f69-4121-812c-822a828947d1"
          },
          {
            "name": "MinistryLabel",
            "expression": "selectedvalue(Ministry[MinistryName])",
            "lineageTag": "56972294-e921-4c0d-ade2-2b5c631757b0"
          },
          {
            "name": "YearLabel",
            "expression": "SELECTEDVALUE('Year'[Year])",
            "lineageTag": "6d2433b6-f9ae-43a5-acd4-c437c24ee255"
          },
          {
            "name": "Yay",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sum(MaturityLevel[Percent Score]), FILTER('MaturityLevel', 'MaturityLevel'[Maturity Level] = \"Level 3 Moderate Progress\"))",
            "lineageTag": "452ad1a5-40ac-4c6f-bbf7-08a4d425236a"
          },
          {
            "name": "Text",
            "expression": "if([Yay] >= 70, UNICHAR(9733), \"\")",
            "lineageTag": "cb026574-4878-41c4-a524-fee5f6458906"
          }
        ],
        "partitions": [
          {
            "name": "Facts",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Values = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Values\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Answers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "emcr_hassitetempproceduresdescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d5fe5d7-f017-4fe6-8501-c4370b8b38c1",
            "sourceColumn": "emcr_hassitetempproceduresdescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_dortosmatchdescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc8740dd-41c5-40f5-8097-d6a4cdb6482e",
            "sourceColumn": "emcr_dortosmatchdescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_itdrplansforcriticalsystemsdescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "024e08db-3a08-4128-a319-e6f1901f3684",
            "sourceColumn": "emcr_itdrplansforcriticalsystemsdescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_altsitesindependentconnectivitydescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42b50396-d857-464b-8889-6536aad2e023",
            "sourceColumn": "emcr_altsitesindependentconnectivitydescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_altsiteshavegeneratordescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50a4535d-70c4-4122-99c0-118c49c4c835",
            "sourceColumn": "emcr_altsiteshavegeneratordescription",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_businesscontinuityexercisesname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02b442e2-ffc2-4ecf-8ffc-8f24007b03bd",
            "sourceColumn": "emcr_businesscontinuityexercisesname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0a1a424-cc73-48b2-9703-1363ec25a6b5",
            "sourceColumn": "Year",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_isescalatedname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed586327-dec1-4bf7-b28f-76e6889c7000",
            "sourceColumn": "emcr_isescalatedname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocaltsiteconnectivityname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c308b28-3a1e-49cb-9ca2-b02451767421",
            "sourceColumn": "emcr_mocaltsiteconnectivityname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_ministryexecapprovalname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f49d13ef-0504-4990-995f-7d38bfc10bc6",
            "sourceColumn": "emcr_ministryexecapprovalname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocaltsitegeneratorname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a0d5e2f-f666-44ac-8ced-2466b0d74e22",
            "sourceColumn": "emcr_mocaltsitegeneratorname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_mocaltsiteprocedurename",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa0e5ea7-a909-4ec2-ac19-3d8132134713",
            "sourceColumn": "emcr_mocaltsiteprocedurename",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_numberofdrills",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4afa0fc2-fe3c-4b4b-9664-d2efa147416a",
            "sourceColumn": "emcr_numberofdrills",
            "sourceProviderType": "nvarchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_dortosmatchname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ef24762-096c-4e30-8758-739c30d5b0d2",
            "sourceColumn": "emcr_dortosmatchname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_altsiteshavegeneratorname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2038035-168c-405b-ac69-b80126f857e6",
            "sourceColumn": "emcr_altsiteshavegeneratorname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_altsitesindependentconnectivityname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d3a27d7-98b5-4a46-aa42-d5b8039f6c75",
            "sourceColumn": "emcr_altsitesindependentconnectivityname",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "MinistryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf9b5554-f831-4827-8fe9-8329f8f6d002",
            "sourceColumn": "MinistryName",
            "sourceProviderType": "nvarchar(160)",
            "summarizeBy": "none"
          },
          {
            "name": "MinistryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef069c95-3f18-4985-a5b9-b957a420e3c8",
            "sourceColumn": "MinistryID",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          },
          {
            "name": "EMCRName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a86a6be3-743a-4956-a5c8-bd7b4dcd1932",
            "sourceColumn": "EMCRName",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          },
          {
            "name": "39. Business Continuity Training Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5505a29-4c60-4d42-a628-474618705b59",
            "sourceColumn": "39. Business Continuity Training Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "58. MOC Training Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b2ab640-3572-4829-a4cd-747f042c8fa5",
            "sourceColumn": "58. MOC Training Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "70. Supply Chain Management Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b777945-cb1c-4cac-9059-9706444d3d5f",
            "sourceColumn": "70. Supply Chain Management Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "64. MOC Exercises Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8b5c832-dcf5-4cc9-9187-9f37e7876bd3",
            "sourceColumn": "64. MOC Exercises Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "46. Business Continuity Exercises Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "962fd09a-4d0a-4cae-9253-73aec8eb7512",
            "sourceColumn": "46. Business Continuity Exercises Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "52. Crisis Management Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea3f93be-5ee2-4c02-8e53-9c8d35b05ed1",
            "sourceColumn": "52. Crisis Management Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "33. Recovery Strategies Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d47ef483-f4bd-4ad7-ac7a-9ccc20d1573b",
            "sourceColumn": "33. Recovery Strategies Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "21. Critical Services Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da1f89b0-f3ba-4fed-9166-f668d08fca96",
            "sourceColumn": "21. Critical Services Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "14. Awareness Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d26f9909-a505-4d06-a7bc-ec9ec6037fe8",
            "sourceColumn": "14. Awareness Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "68. Do critical vendors participate in an annual plan review or assessment?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "660d7743-049c-4ca6-a78a-9b36cfc378d9",
            "sourceColumn": "68. Do critical vendors participate in an annual plan review or assessment?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "67. Are strategies in place for the loss of critical vendors and partners?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa56cce4-ecd6-4087-b300-814d6540f382",
            "sourceColumn": "67. Are strategies in place for the loss of critical vendors and partners?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "66. Have critical dependencies been prioritized based on risk?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a4b075f-e4b6-4147-abfb-62a6a1e063e4",
            "sourceColumn": "66. Have critical dependencies been prioritized based on risk?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "65. Have critical dependencies been identified?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d981f93e-537a-4bc6-a13c-9b9cf59bac79",
            "sourceColumn": "65. Have critical dependencies been identified?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "63. Has the MOC participated in a full-scale or cross government exercise?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a110a1f-4a1c-480b-a514-99f303013209",
            "sourceColumn": "63. Has the MOC participated in a full-scale or cross government exercise?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "62. Has a Functional MOC Exercise occurred?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4793766-79bc-40db-b73e-d2e3c981480a",
            "sourceColumn": "62. Has a Functional MOC Exercise occurred?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "61. Has an MOC Tabletop Exercise been conducted?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a921015f-4d59-4a3d-9308-9cecbacd0424",
            "sourceColumn": "61. Has an MOC Tabletop Exercise been conducted?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "60. Has an MOC Communications Drill been conducted?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5fecae79-ae28-4019-a084-65e2d68c2525",
            "sourceColumn": "60. Has an MOC Communications Drill been conducted?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "59. Has an MOC orientation been provided to MOC staff?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7788ecf-2a47-4f14-aeb4-7fca0f341bdb",
            "sourceColumn": "59. Has an MOC orientation been provided to MOC staff?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "57. Have MOC Leadership (MOC Director and Alternates) been trained?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "272a1637-a67e-4d23-ac2b-52d6d70f52d1",
            "sourceColumn": "57. Have MOC Leadership (MOC Director and Alternates) been trained?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "56. Have MOC staff been trained on their positions and processes?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e069311-cace-4a3d-9145-afdfcdc694c1",
            "sourceColumn": "56. Have MOC staff been trained on their positions and processes?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "55. Is training on the MOC alternate site available to staff?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ea5ca40-9168-40d6-894a-4fd6f22198e4",
            "sourceColumn": "55. Is training on the MOC alternate site available to staff?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "54. Has ICS 100 been offered to BCM/MOC staff?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18d85081-6bc6-453d-8567-09b0ba23f426",
            "sourceColumn": "54. Has ICS 100 been offered to BCM/MOC staff?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "53. Is an MOC overview available to staff?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b25cc3d-9e49-4125-a7e6-6bdbe862d457",
            "sourceColumn": "53. Is an MOC overview available to staff?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "51. Does the MOC have a plan for addressing staffing issues?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1740db96-db50-4bca-b94a-34687a124855",
            "sourceColumn": "51. Does the MOC have a plan for addressing staffing issues?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "50. Does the MOC have a Crisis Communication Plan?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2c0743e-0dfb-430d-b789-5fd030d6f0c8",
            "sourceColumn": "50. Does the MOC have a Crisis Communication Plan?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "48. Does the MOC Director have an alternate?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47f6cd89-8c03-4b57-afb4-d672e01d705f",
            "sourceColumn": "48. Does the MOC Director have an alternate?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "47. Has the MOC Plan been annually reviewed and/or updated?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d6840eb-b69d-4079-bd33-abdd8729cff3",
            "sourceColumn": "47. Has the MOC Plan been annually reviewed and/or updated?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "37. Have Coordinators received training on exercise design and delivery?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48b9e76e-7a13-4f87-9472-10bc202208fb",
            "sourceColumn": "37. Have Coordinators received training on exercise design and delivery?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "36. Have plan owners and coordinators received training on writing recovery procedures?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f244fc22-62d3-4df4-9eca-b57a15819450",
            "sourceColumn": "36. Have plan owners and coordinators received training on writing recovery procedures?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "35. Have plan owners and coordinators received training on identifying and selecting recovery strategies?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72ff3a06-cef4-464c-a71a-c5cc478a2ae5",
            "sourceColumn": "35. Have plan owners and coordinators received training on identifying and selecting recovery strategies?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "34. Have coordinators and plan owners received Business Impact Analysis (BIA) training?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b13a5d06-2fe5-4101-9fdc-e47326ccc33d",
            "sourceColumn": "34. Have coordinators and plan owners received Business Impact Analysis (BIA) training?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "32. Are IT Disaster Recovery (ITDR)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3a22c41-aad2-4c93-bc28-e74a098778b1",
            "sourceColumn": "32. Are IT Disaster Recovery (ITDR)",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "31. Do BCP Recovery Team members have an alternate?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c370eec-1211-48c0-a037-9318aaffb572",
            "sourceColumn": "31. Do BCP Recovery Team members have an alternate?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "30. Have the records and data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50b6fe51-cf61-4d13-81d0-1b5c8c762c6e",
            "sourceColumn": "30. Have the records and data",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "25. Does the BCP contain instructions for recreating lost data?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcf62d94-49bb-413e-9145-86f480dc5e72",
            "sourceColumn": "25. Does the BCP contain instructions for recreating lost data?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "24. Does the BCP contain manual procedures?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7eeb60a2-893a-42f6-9331-9dea5bdc9069",
            "sourceColumn": "24. Does the BCP contain manual procedures?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "23. Does the BCP include cold or warm site set up procedures?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ee770b5-0a14-4f32-9346-6a3e79e9dde0",
            "sourceColumn": "23. Does the BCP include cold or warm site set up procedures?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "22. Does the BCP include notification and activation procedures?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45e9861f-c0e7-4a7b-8f96-eaaddd2d7e12",
            "sourceColumn": "22. Does the BCP include notification and activation procedures?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "20. Are critical service recovery strategies annually reviewed and signed off by Ministry Executive?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb077dc9-6fbf-464b-9ea3-8416c86c074c",
            "sourceColumn": "20. Are critical service recovery strategies annually reviewed and signed off by Ministry Executive?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "19. Are critical services annually reviewed and signed off by Ministry Executive?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ce9cbb1-5c80-4f9d-9fb1-58cd0a5583e0",
            "sourceColumn": "19. Are critical services annually reviewed and signed off by Ministry Executive?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "18. Does the ministry have an up to date list of their critical services?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f59862e-5564-4cdb-9db6-d6735daae55b",
            "sourceColumn": "18. Does the ministry have an up to date list of their critical services?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "13. Is there an annualBusiness Continuity ManagementProgram campaign to promote all staff awareness?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f642e62a-224b-4ad1-89e0-631d786c50fa",
            "sourceColumn": "13. Is there an annualBusiness Continuity ManagementProgram campaign to promote all staff awareness?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "12. Are Business Continuity team members aware of their roles?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dddce6e-3a04-43c3-bcb0-ef356a9c7913",
            "sourceColumn": "12. Are Business Continuity team members aware of their roles?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "11. Are ministry executive aware of the BCM Program?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4bcc5b8-de68-415a-a729-9c5ef1ac1127",
            "sourceColumn": "11. Are ministry executive aware of the BCM Program?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "10. Is there an established network of plan owners and/or coordinators?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abfc3538-1739-42c6-b0a7-5bd4ebe2e4af",
            "sourceColumn": "10. Is there an established network of plan owners and/or coordinators?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "9. Has the Ministry Business Continuity Advisor received training from a Business Continuity ManagementProgram certification body?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ee94d9f-955a-45af-8258-8924eb4fc545",
            "sourceColumn": "9. Has the Ministry Business Continuity Advisor received training from a Business Continuity ManagementProgram certification body?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "7. Does the ministry BCM program have a steering committee? ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bb059ed-ecf4-43fe-af91-eb4d5994928e",
            "sourceColumn": "7. Does the ministry BCM program have a steering committee? ",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "5. Has the ministry implemented a Business Continuity Management Program policy or strategic plan?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02279f7a-431f-4e32-8f63-ee49c7b0801e",
            "sourceColumn": "5. Has the ministry implemented a Business Continuity Management Program policy or strategic plan?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "4. Does the BCM program have an executive sponsor? ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46a38be6-8b2f-4165-9f6d-a49d7a9c228a",
            "sourceColumn": "4. Does the BCM program have an executive sponsor? ",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "3. Is Business Continuity Management Program (BCMP) discussed at the executive level?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ee76b70-4c32-4aa5-8848-b7a38a849f1d",
            "sourceColumn": "3. Is Business Continuity Management Program (BCMP) discussed at the executive level?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "2. Does the ministry have a Ministry BCM Advisor?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1ffd971-d554-4abb-bfba-673e267d6682",
            "sourceColumn": "2. Does the ministry have a Ministry BCM Advisor?",
            "sourceProviderType": "nvarchar(75)",
            "summarizeBy": "none"
          },
          {
            "name": "44. How many Business Continuity Plan functional exercises were conducted in 2025?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cfa9809c-29ec-410d-aabd-f6cd745c0a8b",
            "sourceColumn": "44. How many Business Continuity Plan functional exercises were conducted in 2025?",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "45. How many Business Continuity Plan full scale exercises were conducted in 2025?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35ec8005-8995-4e9b-9a09-f374597f36f3",
            "sourceColumn": "45. How many Business Continuity Plan full scale exercises were conducted in 2025?",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "43. How many Business Continuity Plan tabletop exercises were conducted in 2025?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98243bc5-f7a4-41a7-ab41-e3e5b2378fcb",
            "sourceColumn": "43. How many Business Continuity Plan tabletop exercises were conducted in 2025?",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "41. How many Business Continuity Plan orientations occurred in 2025?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cbd933ae-d814-4dff-9630-b7e6e6e6c96d",
            "sourceColumn": "41. How many Business Continuity Plan orientations occurred in 2025?",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "40. How many Business Continuity Plans (BCPs) does your ministry have?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e7c69c6-6df3-432e-9e71-383310000b30",
            "sourceColumn": "40. How many Business Continuity Plans (BCPs) does your ministry have?",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "8. Leadership Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2407b94d-753c-4124-9f80-c7053028111e",
            "sourceColumn": "8. Leadership Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "15. How many Business Impact Analyses (BIAs) does your ministry require?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a933b8ed-9825-42b3-ba24-e2bd48516a0e",
            "sourceColumn": "15. How many Business Impact Analyses (BIAs) does your ministry require?",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "16. How many Business Impact Analyses were reviewed and updated in 2025?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8e92c38-11c3-4834-af89-3d8a268933e1",
            "sourceColumn": "16. How many Business Impact Analyses were reviewed and updated in 2025?",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "17. How many Business Impacts Analyses (BIAs) were approved or signed by required leadership?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "792f74a6-38da-4471-aff8-7c83c153ed20",
            "sourceColumn": "17. How many Business Impacts Analyses (BIAs) were approved or signed by required leadership?",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "emcr_ministrylistuptodate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b0e5c4c-c307-4970-8b84-b3e7ec0face7",
            "sourceColumn": "emcr_ministrylistuptodate",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "27. BCP Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a56f0676-bd42-4df3-982d-4a4769e67a75",
            "sourceColumn": "27. BCP Comments",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "26. Has the ministry conducted...",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "374158d3-d379-4e85-a959-5a846d99c600",
            "sourceColumn": "26. Has the ministry conducted...",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "28. What methods of communication will be used after a disaster?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a73cab97-1439-4a68-b2d4-e9c314d7ed96",
            "sourceColumn": "28. What methods of communication will be used after a disaster?",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          },
          {
            "name": "29. Does the alternate site have essential infrastructure to maintain operations?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "622981b8-4e86-43d3-84d6-f0d90ca87a19",
            "sourceColumn": "29. Does the alternate site have essential infrastructure to maintain operations?",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          },
          {
            "name": "49. Does the MOC alternate site",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d4a7164-518b-4ecc-851b-6592fbd4ab55",
            "sourceColumn": "49. Does the MOC alternate site",
            "sourceProviderType": "nvarchar(850)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "214fb08d-756b-4154-91bb-c2182414be6c",
        "partitions": [
          {
            "name": "Answers",
            "mode": "directQuery",
            "queryGroup": "Presentation",
            "source": {
              "expression": [
                "let",
                "    Source = trans_Answers",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}