name: Build and Push mqtt-subs branch to OpenShift (dev)

on:
  push:
    branches:
      - mqtt-subs

env:
  IMAGE_NAME: eew-web-api
  IMAGE_TAG: dev
  IMAGE_NAMESPACE: ${{ secrets.OPENSHIFT_IMAGE_NAMESPACE }}
  REGISTRY_URL: ${{ secrets.OPENSHIFT_REGISTRY }}
  FULL_IMAGE_NAME: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to OpenShift internal registry
        run: |
          echo "${{ secrets.OPENSHIFT_TOKEN }}" | docker login ${{ env.REGISTRY_URL }} -u developer --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ env.FULL_IMAGE_NAME }} .

      - name: Push image to OpenShift
        run: |
          docker push ${{ env.FULL_IMAGE_NAME }}

      - name: Confirm pushed image
        run: |
          echo "Image pushed: ${{ env.FULL_IMAGE_NAME }}"